name: Generate Documenatation
on:
  push:
    paths:
      - 'src/**.ts'
      - 'README.md'
      - 'tsconfig.json'
      - 'typedoc.json'

concurrency:
  group: gendocs
  cancel-in-progress: true

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Generate and push docs
        run: |
          npm ci
          npx typedoc
          git config user.name doc-generator-action
          git config user.email doc-generator-action@github.com
          git add docs/
          git commit -m "Generate docs"
          git push
